spring.application.name=posto-combustivel


spring.datasource.url=jdbc:postgresql://localhost:5432/posto-combustivel
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs